services:
  Incoming.Watchdog:
    build: ./Incoming.Watchdog
    image: incoming.watchdog
    container_name: incoming.watchdog
    volumes:
      - C:\workspace:/workspace:ro
      - /var/run/docker.sock:/var/run/docker.sock
