services:
  Incoming.Watchdog:
    image: incoming.watchdog
    container_name: incoming.watchdog
    volumes:
      - C:\workspace:/workspace:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - incoming-queue-network
      - incoming-api-network
  ErrorDb:
    image: errordb
    container_name: errordb
    ports:
      - 1434:1433
    networks:
      - errordb-network
  ItemDb:
    image: itemdb
    container_name: itemdb
    ports:
      - 1435:1433
    networks:
      - itemdb-network
networks:
  incoming-queue-network:
    driver: bridge
  incoming-api-network:
    driver: bridge
  errordb-network:
    driver: bridge
  itemdb-network:
    driver: bridge