services:
  incoming.watchdog:
    build: ./Incoming.Watchdog
    image: incoming.watchdog
    container_name: incoming.watchdog
    volumes:
      - C:\workspace:/workspace:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - incoming-queue-network
      - incoming-api-network
  errordb:
    build: ./Database
    image: database
    container_name: errordb
    environment:
      - SEED=seed_errors.sql
    ports:
      - 1434:1433
    networks:
      - errordb-network
  itemdb:
    build: ./Database
    image: database
    container_name: itemdb
    environment:
      - SEED=seed_items.sql
    ports:
      - 1435:1433
    networks:
      - itemdb-network
networks:
  incoming-queue-network:
    driver: bridge
  incoming-api-network:
    driver: bridge
  errordb-network:
    driver: bridge
  itemdb-network:
    driver: bridge