services:
  Incoming.Watchdog:
    build: ./Incoming.Watchdog
    image: incoming.watchdog
    container_name: incoming.watchdog
    volumes:
      - C:\workspace:/workspace:ro
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
