services:
  itemdb:
    build: ./ItemDb
    platform: linux
    container_name: itemdb
    ports:
      - 1435:1433
    networks:
      - itemdb-network
  incoming.consumer:
    depends_on:
      - itemdb
    build: ./Incoming.Consumer
    platform: windows
    container_name: incoming.consumer
    hostname: incoming.consumer
    networks:
      - itemdb-network
networks:
  itemdb-network:
    driver: nat